# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScanbillSDKExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScanbillSDKExample
  pod 'ScanbillSDK'


  target 'ScanbillSDKExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScanbillSDKExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
